export default {
    ISO_DATE: 'YYYY-MM-DD',
    HUMANIZED: 'humanized',
    RELATIVE: 'relative',
    FULL_DATE: 'LL',
    SIMPLIFIED_DATE: 'MMM DD, YYYY',
    DEFAULT: 'DD MMM YYYY',
    MONTH_DATE: 'yyyy-MM-DD',
    INPUT_DATE: 'DD/MM/YYYY',
    time_hours: 'd:HH:mm:ss',
    time_minutes: 'mm:ss',
    no_zero_time_hours: 'd:H:mm:ss',
    no_zero_time_minutes: 'm:ss',
    time_hours_ms: 'd:HH:mm:ss.SS',
    time_minutes_ms: 'mm:ss.SS',
    no_zero_time_hours_ms: 'd:H:mm:ss.SS',
    no_zero_time_minutes_ms: 'm:ss.SS',
    time_ms: 'mm:ss.SS',
    time_ss_ms: 'ss.SS',
    no_zero_time_ms: 'm:ss.SS',
};
